Repository saurabhs679/AgileMinds-Soen6011summer2023, pull requests merged in 2023-08, with the labels that each got.

#141 Add files via upload
  jobseekr/src/Candidate_Application.html
Labels: Sprint-3

#165 Add files via upload
  MinutesOfMeeting/AgileMinds_Sprint4_MOM9_02-Aug-2023.docx
Labels: Sprint-4

#174 Update README.md
  README.md
Labels: task, Sprint-4
